apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: krjq9yiv7-python
  janus-idp.io/tekton: krjq9yiv7-python
  backstage.io/kubernetes-id: krjq9yiv7-python
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: krjq9yiv7-python
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
